sudo: required
services:
- docker
- docker-compose

before_script: cd deploy
script:
  tag=$TRAVIS_TAG docker-compose build

deploy:
- provider: script
  script: bash aws/deploy.sh $TRAVIS_TAG
  if: tag IN (prod, preprod)i
  on:
     tags: true
