sudo: required
services:
- docker
- docker-compose

before_script: cd deploy
script:
  tag=$TRAVIS_TAG docker-compose build

deploy:
  if: tag IN (prod, preprod)
- provider: script
  script: bash aws/deploy.sh $TRAVIS_TAG

