sudo: required
services:
- docker
- docker-compose

before_deploy : cd deploy

deploy:
- provider: script
  script: bash aws/deploy.sh dev  
  on:
    branch: dev
- provider: script
  script: bash aws/deploy.sh master
  on:
    branch: master

