sudo: required
services:
- docker
- docker-compose

before_script: cd deploy
script:
  if [ -z $TRAVIS_TAG ]; then
       TRAVIS_TAG=dev
  fi; \
  tag=$TRAVIS_TAG docker-compose build

deploy:
- provider: script
  script: bash aws/deploy.sh $TRAVIS_TAG
  on:
    tags: true 
    condition: $TRAVIS_TAG=prod || $TRAVIS_TAG=preprod
