sudo: required
services:
- docker
- docker-compose

before_script: cd deploy
script:
- docker-compose build

deploy:
- provider: script
  script: bash deploy/aws/deploy.sh dev  
  on:
    branch: dev
