version: '3.2'
services:
    wallet:
        image: wallet:${branch}
        build: .
        volumes:
            - /src

    nginx:
        image: onyxchain_wallet:${branch}
        build: 
            context: .
            dockerfile: Dockerfile.srv
            args:
                BRANCH: ${branch}
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - type: volume
              source: .
              target: /host
              volume:
                   noncopy: true
        links:
            - wallet 
